# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import other_pb2 as other__pb2

from other_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\x1a\x0bother.proto\"\xf6\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\r\x12\x11\n\x03sex\x18\x05 \x01(\x0e\x32\x04.Sex\x12\x31\n\rrelationships\x18\n \x03(\x0b\x32\x1a.Person.RelationshipsEntry\x1aJ\n\x12RelationshipsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0e\x32\x14.Person.Relationship:\x02\x38\x01\"3\n\x0cRelationship\x12\n\n\x06PARENT\x10\x00\x12\x0b\n\x07SIBLING\x10\x01\x12\n\n\x06\x46RIEND\x10\x02\"!\n\x06People\x12\x17\n\x06people\x18\x01 \x03(\x0b\x32\x07.PersonP\x00\x62\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSON_RELATIONSHIPSENTRY = _PERSON.nested_types_by_name['RelationshipsEntry']
_PEOPLE = DESCRIPTOR.message_types_by_name['People']
_PERSON_RELATIONSHIP = _PERSON.enum_types_by_name['Relationship']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'RelationshipsEntry' : _reflection.GeneratedProtocolMessageType('RelationshipsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_RELATIONSHIPSENTRY,
    '__module__' : 'spec_pb2'
    # @@protoc_insertion_point(class_scope:Person.RelationshipsEntry)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.RelationshipsEntry)

People = _reflection.GeneratedProtocolMessageType('People', (_message.Message,), {
  'DESCRIPTOR' : _PEOPLE,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:People)
  })
_sym_db.RegisterMessage(People)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON_RELATIONSHIPSENTRY._options = None
  _PERSON_RELATIONSHIPSENTRY._serialized_options = b'8\001'
  _PERSON._serialized_start=28
  _PERSON._serialized_end=274
  _PERSON_RELATIONSHIPSENTRY._serialized_start=147
  _PERSON_RELATIONSHIPSENTRY._serialized_end=221
  _PERSON_RELATIONSHIP._serialized_start=223
  _PERSON_RELATIONSHIP._serialized_end=274
  _PEOPLE._serialized_start=276
  _PEOPLE._serialized_end=309
# @@protoc_insertion_point(module_scope)
