(Proto2
 ((Package unittest)
  (Option (optimize_for) SPEED)
  (Message
   TestAllTypes
   ((Message NestedMessage () ((MessageField optional int32 bb 1 ())) () () ())
    (Enum NestedEnum ((EnumField FOO 1 ()) (EnumField BAR 2 ()) (EnumField BAZ 3 ()) (EnumField NEG -1 ())) () ()))
   ((MessageField optional int32 optional_int32 1 ())
    (MessageField optional int64 optional_int64 2 ())
    (MessageField optional uint32 optional_uint32 3 ())
    (MessageField optional uint64 optional_uint64 4 ())
    (MessageField optional sint32 optional_sint32 5 ())
    (MessageField optional sint64 optional_sint64 6 ())
    (MessageField optional fixed32 optional_fixed32 7 ())
    (MessageField optional fixed64 optional_fixed64 8 ())
    (MessageField optional sfixed32 optional_sfixed32 9 ())
    (MessageField optional sfixed64 optional_sfixed64 10 ())
    (MessageField optional float optional_float 11 ())
    (MessageField optional double optional_double 12 ())
    (MessageField optional bool optional_bool 13 ())
    (MessageField optional string optional_string 14 ())
    (MessageField optional bytes optional_bytes 15 ())
    (MessageGroupField optional OptionalGroup 16 () ((MessageField optional int32 a 17 ())) () () ())
    (MessageField optional NestedMessage optional_nested_message 18 ())
    (MessageField optional ForeignMessage optional_foreign_message 19 ())
    (MessageField optional NestedEnum optional_nested_enum 21 ())
    (MessageField optional ForeignEnum optional_foreign_enum 22 ())
    (MessageField optional string optional_string_piece 24 ((Option (ctype) STRING_PIECE)))
    (MessageField optional string optional_cord 25 ((Option (ctype) CORD)))
    (MessageField optional NestedMessage optional_lazy_message 27 ((Option (lazy) #t)))
    (MessageField repeated int32 repeated_int32 31 ())
    (MessageField repeated int64 repeated_int64 32 ())
    (MessageField repeated uint32 repeated_uint32 33 ())
    (MessageField repeated uint64 repeated_uint64 34 ())
    (MessageField repeated sint32 repeated_sint32 35 ())
    (MessageField repeated sint64 repeated_sint64 36 ())
    (MessageField repeated fixed32 repeated_fixed32 37 ())
    (MessageField repeated fixed64 repeated_fixed64 38 ())
    (MessageField repeated sfixed32 repeated_sfixed32 39 ())
    (MessageField repeated sfixed64 repeated_sfixed64 40 ())
    (MessageField repeated float repeated_float 41 ())
    (MessageField repeated double repeated_double 42 ())
    (MessageField repeated bool repeated_bool 43 ())
    (MessageField repeated string repeated_string 44 ())
    (MessageField repeated bytes repeated_bytes 45 ())
    (MessageGroupField repeated RepeatedGroup 46 () ((MessageField optional int32 a 47 ())) () () ())
    (MessageField repeated NestedMessage repeated_nested_message 48 ())
    (MessageField repeated ForeignMessage repeated_foreign_message 49 ())
    (MessageField repeated NestedEnum repeated_nested_enum 51 ())
    (MessageField repeated ForeignEnum repeated_foreign_enum 52 ())
    (MessageField repeated string repeated_string_piece 54 ((Option (ctype) STRING_PIECE)))
    (MessageField repeated string repeated_cord 55 ((Option (ctype) CORD)))
    (MessageField repeated NestedMessage repeated_lazy_message 57 ((Option (lazy) #t)))
    (MessageField optional int32 default_int32 61 ((Option (default) 41)))
    (MessageField optional int64 default_int64 62 ((Option (default) 42)))
    (MessageField optional uint32 default_uint32 63 ((Option (default) 43)))
    (MessageField optional uint64 default_uint64 64 ((Option (default) 44)))
    (MessageField optional sint32 default_sint32 65 ((Option (default) -45)))
    (MessageField optional sint64 default_sint64 66 ((Option (default) 46)))
    (MessageField optional fixed32 default_fixed32 67 ((Option (default) 47)))
    (MessageField optional fixed64 default_fixed64 68 ((Option (default) 48)))
    (MessageField optional sfixed32 default_sfixed32 69 ((Option (default) 49)))
    (MessageField optional sfixed64 default_sfixed64 70 ((Option (default) -50)))
    (MessageField optional float default_float 71 ((Option (default) 51.5)))
    (MessageField optional double default_double 72 ((Option (default) 52000.0)))
    (MessageField optional bool default_bool 73 ((Option (default) #t)))
    (MessageField optional string default_string 74 ((Option (default) "hello")))
    (MessageField optional bytes default_bytes 75 ((Option (default) "world")))
    (MessageField optional NestedEnum default_nested_enum 81 ((Option (default) BAR)))
    (MessageField optional ForeignEnum default_foreign_enum 82 ((Option (default) FOREIGN_BAR)))
    (MessageField optional string default_string_piece 84 ((Option (ctype) STRING_PIECE) (Option (default) "abc")))
    (MessageField optional string default_cord 85 ((Option (ctype) CORD) (Option (default) "123")))
    (MessageOneOfField
     oneof_field
     ((MessageField optional uint32 oneof_uint32 111 ())
      (MessageField optional NestedMessage oneof_nested_message 112 ())
      (MessageField optional string oneof_string 113 ())
      (MessageField optional bytes oneof_bytes 114 ()))))
   ()
   ()
   ())
  (Message
   NestedTestAllTypes
   ()
   ((MessageField optional NestedTestAllTypes child 1 ())
    (MessageField optional TestAllTypes payload 2 ())
    (MessageField repeated NestedTestAllTypes repeated_child 3 ())
    (MessageField optional NestedTestAllTypes lazy_child 4 ((Option (lazy) #t)))
    (MessageField optional TestAllTypes eager_child 5 ((Option (lazy) #f))))
   ()
   ()
   ())
  (Message
   TestDeprecatedFields
   ()
   ((MessageField optional int32 deprecated_int32 1 ((Option (deprecated) #t)))
    (MessageOneOfField
     oneof_fields
     ((MessageField optional int32 deprecated_int32_in_oneof 2 ((Option (deprecated) #t))))))
   ()
   ()
   ())
  (Message TestDeprecatedMessage () () ((Option (deprecated) #t)) () ())
  (Message ForeignMessage () ((MessageField optional int32 c 1 ()) (MessageField optional int32 d 2 ())) () () ())
  (Enum ForeignEnum ((EnumField FOREIGN_FOO 4 ()) (EnumField FOREIGN_BAR 5 ()) (EnumField FOREIGN_BAZ 6 ())) () ())
  (Message TestReservedFields () () () ((2 15 (Range 9 11)) ("bar" "baz")) ())
  (Enum TestReservedEnumFields ((EnumField UNKNOWN 0 ())) () ((2 15 (Range 9 11)) ("bar" "baz")))
  (Message TestAllExtensions () () () () (((Range 1 max))))
  (Extend
   TestAllExtensions
   ((MessageField optional int32 optional_int32_extension 1 ())
    (MessageField optional int64 optional_int64_extension 2 ())
    (MessageField optional uint32 optional_uint32_extension 3 ())
    (MessageField optional uint64 optional_uint64_extension 4 ())
    (MessageField optional sint32 optional_sint32_extension 5 ())
    (MessageField optional sint64 optional_sint64_extension 6 ())
    (MessageField optional fixed32 optional_fixed32_extension 7 ())
    (MessageField optional fixed64 optional_fixed64_extension 8 ())
    (MessageField optional sfixed32 optional_sfixed32_extension 9 ())
    (MessageField optional sfixed64 optional_sfixed64_extension 10 ())
    (MessageField optional float optional_float_extension 11 ())
    (MessageField optional double optional_double_extension 12 ())
    (MessageField optional bool optional_bool_extension 13 ())
    (MessageField optional string optional_string_extension 14 ())
    (MessageField optional bytes optional_bytes_extension 15 ())
    (MessageGroupField optional OptionalGroup_extension 16 () ((MessageField optional int32 a 17 ())) () () ())
    (MessageField optional TestAllTypes.NestedMessage optional_nested_message_extension 18 ())
    (MessageField optional ForeignMessage optional_foreign_message_extension 19 ())
    (MessageField optional TestAllTypes.NestedEnum optional_nested_enum_extension 21 ())
    (MessageField optional ForeignEnum optional_foreign_enum_extension 22 ())
    (MessageField optional string optional_string_piece_extension 24 ((Option (ctype) STRING_PIECE)))
    (MessageField optional string optional_cord_extension 25 ((Option (ctype) CORD)))
    (MessageField optional TestAllTypes.NestedMessage optional_lazy_message_extension 27 ((Option (lazy) #t)))
    (MessageField repeated int32 repeated_int32_extension 31 ())
    (MessageField repeated int64 repeated_int64_extension 32 ())
    (MessageField repeated uint32 repeated_uint32_extension 33 ())
    (MessageField repeated uint64 repeated_uint64_extension 34 ())
    (MessageField repeated sint32 repeated_sint32_extension 35 ())
    (MessageField repeated sint64 repeated_sint64_extension 36 ())
    (MessageField repeated fixed32 repeated_fixed32_extension 37 ())
    (MessageField repeated fixed64 repeated_fixed64_extension 38 ())
    (MessageField repeated sfixed32 repeated_sfixed32_extension 39 ())
    (MessageField repeated sfixed64 repeated_sfixed64_extension 40 ())
    (MessageField repeated float repeated_float_extension 41 ())
    (MessageField repeated double repeated_double_extension 42 ())
    (MessageField repeated bool repeated_bool_extension 43 ())
    (MessageField repeated string repeated_string_extension 44 ())
    (MessageField repeated bytes repeated_bytes_extension 45 ())
    (MessageGroupField repeated RepeatedGroup_extension 46 () ((MessageField optional int32 a 47 ())) () () ())
    (MessageField repeated TestAllTypes.NestedMessage repeated_nested_message_extension 48 ())
    (MessageField repeated ForeignMessage repeated_foreign_message_extension 49 ())
    (MessageField repeated TestAllTypes.NestedEnum repeated_nested_enum_extension 51 ())
    (MessageField repeated ForeignEnum repeated_foreign_enum_extension 52 ())
    (MessageField repeated string repeated_string_piece_extension 54 ((Option (ctype) STRING_PIECE)))
    (MessageField repeated string repeated_cord_extension 55 ((Option (ctype) CORD)))
    (MessageField repeated TestAllTypes.NestedMessage repeated_lazy_message_extension 57 ((Option (lazy) #t)))
    (MessageField optional int32 default_int32_extension 61 ((Option (default) 41)))
    (MessageField optional int64 default_int64_extension 62 ((Option (default) 42)))
    (MessageField optional uint32 default_uint32_extension 63 ((Option (default) 43)))
    (MessageField optional uint64 default_uint64_extension 64 ((Option (default) 44)))
    (MessageField optional sint32 default_sint32_extension 65 ((Option (default) -45)))
    (MessageField optional sint64 default_sint64_extension 66 ((Option (default) 46)))
    (MessageField optional fixed32 default_fixed32_extension 67 ((Option (default) 47)))
    (MessageField optional fixed64 default_fixed64_extension 68 ((Option (default) 48)))
    (MessageField optional sfixed32 default_sfixed32_extension 69 ((Option (default) 49)))
    (MessageField optional sfixed64 default_sfixed64_extension 70 ((Option (default) -50)))
    (MessageField optional float default_float_extension 71 ((Option (default) 51.5)))
    (MessageField optional double default_double_extension 72 ((Option (default) 52000.0)))
    (MessageField optional bool default_bool_extension 73 ((Option (default) #t)))
    (MessageField optional string default_string_extension 74 ((Option (default) "hello")))
    (MessageField optional bytes default_bytes_extension 75 ((Option (default) "world")))
    (MessageField optional TestAllTypes.NestedEnum default_nested_enum_extension 81 ((Option (default) BAR)))
    (MessageField optional ForeignEnum default_foreign_enum_extension 82 ((Option (default) FOREIGN_BAR)))
    (MessageField
     optional
     string
     default_string_piece_extension
     84
     ((Option (ctype) STRING_PIECE) (Option (default) "abc")))
    (MessageField optional string default_cord_extension 85 ((Option (ctype) CORD) (Option (default) "123")))
    (MessageField optional uint32 oneof_uint32_extension 111 ())
    (MessageField optional TestAllTypes.NestedMessage oneof_nested_message_extension 112 ())
    (MessageField optional string oneof_string_extension 113 ())
    (MessageField optional bytes oneof_bytes_extension 114 ())))
  (Message
   TestGroup
   ()
   ((MessageGroupField optional OptionalGroup 16 () ((MessageField optional int32 a 17 ())) () () ())
    (MessageField optional ForeignEnum optional_foreign_enum 22 ()))
   ()
   ()
   ())
  (Message TestGroupExtension () () () () (((Range 1 max))))
  (Message
   TestNestedExtension
   ((Extend
     TestAllExtensions
     ((MessageField optional string test 1002 ((Option (default) "test")))
      (MessageField optional string nested_string_extension 1003 ())))
    (Extend
     TestGroupExtension
     ((MessageGroupField optional OptionalGroup_extension 16 () ((MessageField optional int32 a 17 ())) () () ())
      (MessageField optional ForeignEnum optional_foreign_enum_extension 22 ()))))
   ()
   ()
   ()
   ())
  (Message
   TestChildExtension
   ()
   ((MessageField optional string a 1 ())
    (MessageField optional string b 2 ())
    (MessageField optional TestAllExtensions optional_extension 3 ()))
   ()
   ()
   ())
  (Message
   TestChildExtensionData
   ((Message
     NestedTestAllExtensionsData
     ((Message
       NestedDynamicExtensions
       ()
       ((MessageField optional int32 a 1 ()) (MessageField optional int32 b 2 ()))
       ()
       ()
       ()))
     ((MessageField optional NestedDynamicExtensions dynamic 409707008 ()))
     ()
     ()
     ()))
   ((MessageField optional string a 1 ())
    (MessageField optional string b 2 ())
    (MessageField optional NestedTestAllExtensionsData optional_extension 3 ()))
   ()
   ()
   ())
  (Message
   TestNestedChildExtension
   ()
   ((MessageField optional int32 a 1 ()) (MessageField optional TestChildExtension child 2 ()))
   ()
   ()
   ())
  (Message
   TestNestedChildExtensionData
   ()
   ((MessageField optional int32 a 1 ()) (MessageField optional TestChildExtensionData child 2 ()))
   ()
   ()
   ())
  (Message
   TestRequired
   ((Extend
     TestAllExtensions
     ((MessageField optional TestRequired single 1000 ()) (MessageField repeated TestRequired multi 1001 ()))))
   ((MessageField required int32 a 1 ())
    (MessageField optional int32 dummy2 2 ())
    (MessageField required int32 b 3 ())
    (MessageField optional int32 dummy4 4 ())
    (MessageField optional int32 dummy5 5 ())
    (MessageField optional int32 dummy6 6 ())
    (MessageField optional int32 dummy7 7 ())
    (MessageField optional int32 dummy8 8 ())
    (MessageField optional int32 dummy9 9 ())
    (MessageField optional int32 dummy10 10 ())
    (MessageField optional int32 dummy11 11 ())
    (MessageField optional int32 dummy12 12 ())
    (MessageField optional int32 dummy13 13 ())
    (MessageField optional int32 dummy14 14 ())
    (MessageField optional int32 dummy15 15 ())
    (MessageField optional int32 dummy16 16 ())
    (MessageField optional int32 dummy17 17 ())
    (MessageField optional int32 dummy18 18 ())
    (MessageField optional int32 dummy19 19 ())
    (MessageField optional int32 dummy20 20 ())
    (MessageField optional int32 dummy21 21 ())
    (MessageField optional int32 dummy22 22 ())
    (MessageField optional int32 dummy23 23 ())
    (MessageField optional int32 dummy24 24 ())
    (MessageField optional int32 dummy25 25 ())
    (MessageField optional int32 dummy26 26 ())
    (MessageField optional int32 dummy27 27 ())
    (MessageField optional int32 dummy28 28 ())
    (MessageField optional int32 dummy29 29 ())
    (MessageField optional int32 dummy30 30 ())
    (MessageField optional int32 dummy31 31 ())
    (MessageField optional int32 dummy32 32 ())
    (MessageField required int32 c 33 ())
    (MessageField optional ForeignMessage optional_foreign 34 ()))
   ()
   ()
   ())
  (Message
   TestRequiredForeign
   ()
   ((MessageField optional TestRequired optional_message 1 ())
    (MessageField repeated TestRequired repeated_message 2 ())
    (MessageField optional int32 dummy 3 ())
    (MessageField optional NestedTestAllTypes optional_lazy_message 4 ((Option (lazy) #t))))
   ()
   ()
   ())
  (Message
   TestRequiredMessage
   ()
   ((MessageField optional TestRequired optional_message 1 ())
    (MessageField repeated TestRequired repeated_message 2 ())
    (MessageField required TestRequired required_message 3 ()))
   ()
   ()
   ())
  (Message
   TestNestedRequiredForeign
   ()
   ((MessageField optional TestNestedRequiredForeign child 1 ())
    (MessageField optional TestRequiredForeign payload 2 ())
    (MessageField optional int32 dummy 3 ()))
   ()
   ()
   ())
  (Message TestForeignNested () ((MessageField optional TestAllTypes.NestedMessage foreign_nested 1 ())) () () ())
  (Message TestEmptyMessage () () () () ())
  (Message TestEmptyMessageWithExtensions () () () () (((Range 1 max))))
  (Message
   TestPickleNestedMessage
   ((Message
     NestedMessage
     ((Message NestedNestedMessage () ((MessageField optional int32 cc 1 ())) () () ()))
     ((MessageField optional int32 bb 1 ()))
     ()
     ()
     ()))
   ()
   ()
   ()
   ())
  (Message TestMultipleExtensionRanges () () () () ((42) ((Range 4143 4243)) ((Range 65536 max))))
  (Message
   TestReallyLargeTagNumber
   ()
   ((MessageField optional int32 a 1 ()) (MessageField optional int32 bb 268435455 ()))
   ()
   ()
   ())
  (Message
   TestRecursiveMessage
   ()
   ((MessageField optional TestRecursiveMessage a 1 ()) (MessageField optional int32 i 2 ()))
   ()
   ()
   ())
  (Message
   TestMutualRecursionA
   ((Message SubMessage () ((MessageField optional TestMutualRecursionB b 1 ())) () () ()))
   ((MessageField optional TestMutualRecursionB bb 1 ())
    (MessageGroupField
     optional
     SubGroup
     2
     ()
     ((MessageField optional SubMessage sub_message 3 ()) (MessageField optional TestAllTypes not_in_this_scc 4 ()))
     ()
     ()
     ()))
   ()
   ()
   ())
  (Message
   TestMutualRecursionB
   ()
   ((MessageField optional TestMutualRecursionA a 1 ()) (MessageField optional int32 optional_int32 2 ()))
   ()
   ()
   ())
  (Message
   TestIsInitialized
   ((Message
     SubMessage
     ()
     ((MessageGroupField optional SubGroup 1 () ((MessageField required int32 i 2 ())) () () ()))
     ()
     ()
     ()))
   ((MessageField optional SubMessage sub_message 1 ()))
   ()
   ()
   ())
  (Message
   TestDupFieldNumber
   ()
   ((MessageField optional int32 a 1 ())
    (MessageGroupField optional Foo 2 () ((MessageField optional int32 a 1 ())) () () ())
    (MessageGroupField optional Bar 3 () ((MessageField optional int32 a 1 ())) () () ()))
   ()
   ()
   ())
  (Message TestEagerMessage () ((MessageField optional TestAllTypes sub_message 1 ((Option (lazy) #f)))) () () ())
  (Message TestLazyMessage () ((MessageField optional TestAllTypes sub_message 1 ((Option (lazy) #t)))) () () ())
  (Message
   TestEagerMaybeLazy
   ((Message NestedMessage () ((MessageField optional TestPackedTypes packed 1 ())) () () ()))
   ((MessageField optional TestAllTypes message_foo 1 ())
    (MessageField optional TestAllTypes message_bar 2 ())
    (MessageField optional NestedMessage message_baz 3 ()))
   ()
   ()
   ())
  (Message
   TestNestedMessageHasBits
   ((Message
     NestedMessage
     ()
     ((MessageField repeated int32 nestedmessage_repeated_int32 1 ())
      (MessageField repeated ForeignMessage nestedmessage_repeated_foreignmessage 2 ()))
     ()
     ()
     ()))
   ((MessageField optional NestedMessage optional_nested_message 1 ()))
   ()
   ()
   ())
  (Enum
   TestEnumWithDupValue
   ((EnumField FOO1 1 ()) (EnumField BAR1 2 ()) (EnumField BAZ 3 ()) (EnumField FOO2 1 ()) (EnumField BAR2 2 ()))
   ((Option (allow_alias) #t))
   ())
  (Enum
   TestSparseEnum
   ((EnumField SPARSE_A 123 ())
    (EnumField SPARSE_B 62374 ())
    (EnumField SPARSE_C 12589234 ())
    (EnumField SPARSE_D -15 ())
    (EnumField SPARSE_E -53452 ())
    (EnumField SPARSE_F 0 ())
    (EnumField SPARSE_G 2 ()))
   ()
   ())
  (Message
   TestCamelCaseFieldNames
   ()
   ((MessageField optional int32 PrimitiveField 1 ())
    (MessageField optional string StringField 2 ())
    (MessageField optional ForeignEnum EnumField 3 ())
    (MessageField optional ForeignMessage MessageField 4 ())
    (MessageField optional string StringPieceField 5 ((Option (ctype) STRING_PIECE)))
    (MessageField optional string CordField 6 ((Option (ctype) CORD)))
    (MessageField repeated int32 RepeatedPrimitiveField 7 ())
    (MessageField repeated string RepeatedStringField 8 ())
    (MessageField repeated ForeignEnum RepeatedEnumField 9 ())
    (MessageField repeated ForeignMessage RepeatedMessageField 10 ())
    (MessageField repeated string RepeatedStringPieceField 11 ((Option (ctype) STRING_PIECE)))
    (MessageField repeated string RepeatedCordField 12 ((Option (ctype) CORD))))
   ()
   ()
   ())
  (Message
   TestFieldOrderings
   ((Message NestedMessage () ((MessageField optional int64 oo 2 ()) (MessageField optional int32 bb 1 ())) () () ()))
   ((MessageField optional string my_string 11 ())
    (MessageField optional int64 my_int 1 ())
    (MessageField optional float my_float 101 ())
    (MessageField optional NestedMessage optional_nested_message 200 ()))
   ()
   ()
   (((Range 2 10)) ((Range 12 100))))
  (Extend
   TestFieldOrderings
   ((MessageField optional string my_extension_string 50 ()) (MessageField optional int32 my_extension_int 5 ())))
  (Message
   TestExtensionOrderings1
   ((Extend TestFieldOrderings ((MessageField optional TestExtensionOrderings1 test_ext_orderings1 13 ()))))
   ((MessageField optional string my_string 1 ()))
   ()
   ()
   ())
  (Message
   TestExtensionOrderings2
   ((Extend TestFieldOrderings ((MessageField optional TestExtensionOrderings2 test_ext_orderings2 12 ())))
    (Message
     TestExtensionOrderings3
     ((Extend TestFieldOrderings ((MessageField optional TestExtensionOrderings3 test_ext_orderings3 14 ()))))
     ((MessageField optional string my_string 1 ()))
     ()
     ()
     ()))
   ((MessageField optional string my_string 1 ()))
   ()
   ()
   ())
  (Message
   TestExtremeDefaultValues
   ()
   ((MessageField optional bytes escaped_bytes 1 ((Option (default) "\u0000\u0001\a\b\f\n\r\t\v\\'\"þ")))
    (MessageField optional uint32 large_uint32 2 ((Option (default) 4294967295)))
    (MessageField optional uint64 large_uint64 3 ((Option (default) 18446744073709551615)))
    (MessageField optional int32 small_int32 4 ((Option (default) -2147483647)))
    (MessageField optional int64 small_int64 5 ((Option (default) -9223372036854775807)))
    (MessageField optional int32 really_small_int32 21 ((Option (default) -2147483648)))
    (MessageField optional int64 really_small_int64 22 ((Option (default) -9223372036854775808)))
    (MessageField optional string utf8_string 6 ((Option (default) "á\u0088´")))
    (MessageField optional float zero_float 7 ((Option (default) 0)))
    (MessageField optional float one_float 8 ((Option (default) 1)))
    (MessageField optional float small_float 9 ((Option (default) 1.5)))
    (MessageField optional float negative_one_float 10 ((Option (default) -1)))
    (MessageField optional float negative_float 11 ((Option (default) -1.5)))
    (MessageField optional float large_float 12 ((Option (default) 200000000.0)))
    (MessageField optional float small_negative_float 13 ((Option (default) -8e-28)))
    (MessageField optional double inf_double 14 ((Option (default) +inf.0)))
    (MessageField optional double neg_inf_double 15 ((Option (default) -inf.0)))
    (MessageField optional double nan_double 16 ((Option (default) +nan.0)))
    (MessageField optional float inf_float 17 ((Option (default) +inf.0)))
    (MessageField optional float neg_inf_float 18 ((Option (default) -inf.0)))
    (MessageField optional float nan_float 19 ((Option (default) +nan.0)))
    (MessageField optional string cpp_trigraph 20 ((Option (default) "? ? ?? ?? ??? ??/ ??-")))
    (MessageField optional string string_with_zero 23 ((Option (default) "hel\u0000lo")))
    (MessageField optional bytes bytes_with_zero 24 ((Option (default) "wor\u0000ld")))
    (MessageField optional string string_piece_with_zero 25 ((Option (ctype) STRING_PIECE) (Option (default) "ab\u0000c")))
    (MessageField optional string cord_with_zero 26 ((Option (ctype) CORD) (Option (default) "12\u00003")))
    (MessageField optional string replacement_string 27 ((Option (default) "${unknown}"))))
   ()
   ()
   ())
  (Message SparseEnumMessage () ((MessageField optional TestSparseEnum sparse_enum 1 ())) () () ())
  (Message OneString () ((MessageField optional string data 1 ())) () () ())
  (Message MoreString () ((MessageField repeated string data 1 ())) () () ())
  (Message OneBytes () ((MessageField optional bytes data 1 ())) () () ())
  (Message MoreBytes () ((MessageField repeated bytes data 1 ())) () () ())
  (Message
   ManyOptionalString
   ()
   ((MessageField optional string str1 1 ())
    (MessageField optional string str2 2 ())
    (MessageField optional string str3 3 ())
    (MessageField optional string str4 4 ())
    (MessageField optional string str5 5 ())
    (MessageField optional string str6 6 ())
    (MessageField optional string str7 7 ())
    (MessageField optional string str8 8 ())
    (MessageField optional string str9 9 ())
    (MessageField optional string str10 10 ())
    (MessageField optional string str11 11 ())
    (MessageField optional string str12 12 ())
    (MessageField optional string str13 13 ())
    (MessageField optional string str14 14 ())
    (MessageField optional string str15 15 ())
    (MessageField optional string str16 16 ())
    (MessageField optional string str17 17 ())
    (MessageField optional string str18 18 ())
    (MessageField optional string str19 19 ())
    (MessageField optional string str20 20 ())
    (MessageField optional string str21 21 ())
    (MessageField optional string str22 22 ())
    (MessageField optional string str23 23 ())
    (MessageField optional string str24 24 ())
    (MessageField optional string str25 25 ())
    (MessageField optional string str26 26 ())
    (MessageField optional string str27 27 ())
    (MessageField optional string str28 28 ())
    (MessageField optional string str29 29 ())
    (MessageField optional string str30 30 ())
    (MessageField optional string str31 31 ())
    (MessageField optional string str32 32 ()))
   ()
   ()
   ())
  (Message Int32Message () ((MessageField optional int32 data 1 ())) () () ())
  (Message Uint32Message () ((MessageField optional uint32 data 1 ())) () () ())
  (Message Int64Message () ((MessageField optional int64 data 1 ())) () () ())
  (Message Uint64Message () ((MessageField optional uint64 data 1 ())) () () ())
  (Message BoolMessage () ((MessageField optional bool data 1 ())) () () ())
  (Message
   TestOneof
   ()
   ((MessageOneOfField
     foo
     ((MessageField optional int32 foo_int 1 ())
      (MessageField optional string foo_string 2 ())
      (MessageField optional TestAllTypes foo_message 3 ())
      (MessageGroupField
       optional
       FooGroup
       4
       ()
       ((MessageField optional int32 a 5 ()) (MessageField optional string b 6 ()))
       ()
       ()
       ()))))
   ()
   ()
   ())
  (Message
   TestOneofBackwardsCompatible
   ()
   ((MessageField optional int32 foo_int 1 ())
    (MessageField optional string foo_string 2 ())
    (MessageField optional TestAllTypes foo_message 3 ())
    (MessageGroupField
     optional
     FooGroup
     4
     ()
     ((MessageField optional int32 a 5 ()) (MessageField optional string b 6 ()))
     ()
     ()
     ()))
   ()
   ()
   ())
  (Message
   TestOneof2
   ((Message
     NestedMessage
     ()
     ((MessageField optional int64 moo_int 1 ()) (MessageField repeated int32 corge_int 2 ()))
     ()
     ()
     ())
    (Enum NestedEnum ((EnumField FOO 1 ()) (EnumField BAR 2 ()) (EnumField BAZ 3 ())) () ()))
   ((MessageOneOfField
     foo
     ((MessageField optional int32 foo_int 1 ())
      (MessageField optional string foo_string 2 ())
      (MessageField optional string foo_cord 3 ((Option (ctype) CORD)))
      (MessageField optional string foo_string_piece 4 ((Option (ctype) STRING_PIECE)))
      (MessageField optional bytes foo_bytes 5 ())
      (MessageField optional NestedEnum foo_enum 6 ())
      (MessageField optional NestedMessage foo_message 7 ())
      (MessageGroupField
       optional
       FooGroup
       8
       ()
       ((MessageField optional int32 a 9 ()) (MessageField optional string b 10 ()))
       ()
       ()
       ())
      (MessageField optional NestedMessage foo_lazy_message 11 ((Option (lazy) #t)))))
    (MessageOneOfField
     bar
     ((MessageField optional int32 bar_int 12 ((Option (default) 5)))
      (MessageField optional string bar_string 13 ((Option (default) "STRING")))
      (MessageField optional string bar_cord 14 ((Option (ctype) CORD) (Option (default) "CORD")))
      (MessageField optional string bar_string_piece 15 ((Option (ctype) STRING_PIECE) (Option (default) "SPIECE")))
      (MessageField optional bytes bar_bytes 16 ((Option (default) "BYTES")))
      (MessageField optional NestedEnum bar_enum 17 ((Option (default) BAR)))
      (MessageField optional string bar_string_with_empty_default 20 ((Option (default) "")))
      (MessageField optional string bar_cord_with_empty_default 21 ((Option (ctype) CORD) (Option (default) "")))
      (MessageField
       optional
       string
       bar_string_piece_with_empty_default
       22
       ((Option (ctype) STRING_PIECE) (Option (default) "")))
      (MessageField optional bytes bar_bytes_with_empty_default 23 ((Option (default) "")))))
    (MessageField optional int32 baz_int 18 ())
    (MessageField optional string baz_string 19 ((Option (default) "BAZ"))))
   ()
   ()
   ())
  (Message
   TestRequiredOneof
   ((Message NestedMessage () ((MessageField required double required_double 1 ())) () () ()))
   ((MessageOneOfField
     foo
     ((MessageField optional int32 foo_int 1 ())
      (MessageField optional string foo_string 2 ())
      (MessageField optional NestedMessage foo_message 3 ()))))
   ()
   ()
   ())
  (Message
   TestPackedTypes
   ()
   ((MessageField repeated int32 packed_int32 90 ((Option (packed) #t)))
    (MessageField repeated int64 packed_int64 91 ((Option (packed) #t)))
    (MessageField repeated uint32 packed_uint32 92 ((Option (packed) #t)))
    (MessageField repeated uint64 packed_uint64 93 ((Option (packed) #t)))
    (MessageField repeated sint32 packed_sint32 94 ((Option (packed) #t)))
    (MessageField repeated sint64 packed_sint64 95 ((Option (packed) #t)))
    (MessageField repeated fixed32 packed_fixed32 96 ((Option (packed) #t)))
    (MessageField repeated fixed64 packed_fixed64 97 ((Option (packed) #t)))
    (MessageField repeated sfixed32 packed_sfixed32 98 ((Option (packed) #t)))
    (MessageField repeated sfixed64 packed_sfixed64 99 ((Option (packed) #t)))
    (MessageField repeated float packed_float 100 ((Option (packed) #t)))
    (MessageField repeated double packed_double 101 ((Option (packed) #t)))
    (MessageField repeated bool packed_bool 102 ((Option (packed) #t)))
    (MessageField repeated ForeignEnum packed_enum 103 ((Option (packed) #t))))
   ()
   ()
   ())
  (Message
   TestUnpackedTypes
   ()
   ((MessageField repeated int32 unpacked_int32 90 ((Option (packed) #f)))
    (MessageField repeated int64 unpacked_int64 91 ((Option (packed) #f)))
    (MessageField repeated uint32 unpacked_uint32 92 ((Option (packed) #f)))
    (MessageField repeated uint64 unpacked_uint64 93 ((Option (packed) #f)))
    (MessageField repeated sint32 unpacked_sint32 94 ((Option (packed) #f)))
    (MessageField repeated sint64 unpacked_sint64 95 ((Option (packed) #f)))
    (MessageField repeated fixed32 unpacked_fixed32 96 ((Option (packed) #f)))
    (MessageField repeated fixed64 unpacked_fixed64 97 ((Option (packed) #f)))
    (MessageField repeated sfixed32 unpacked_sfixed32 98 ((Option (packed) #f)))
    (MessageField repeated sfixed64 unpacked_sfixed64 99 ((Option (packed) #f)))
    (MessageField repeated float unpacked_float 100 ((Option (packed) #f)))
    (MessageField repeated double unpacked_double 101 ((Option (packed) #f)))
    (MessageField repeated bool unpacked_bool 102 ((Option (packed) #f)))
    (MessageField repeated ForeignEnum unpacked_enum 103 ((Option (packed) #f))))
   ()
   ()
   ())
  (Message TestPackedExtensions () () () () (((Range 1 max))))
  (Extend
   TestPackedExtensions
   ((MessageField repeated int32 packed_int32_extension 90 ((Option (packed) #t)))
    (MessageField repeated int64 packed_int64_extension 91 ((Option (packed) #t)))
    (MessageField repeated uint32 packed_uint32_extension 92 ((Option (packed) #t)))
    (MessageField repeated uint64 packed_uint64_extension 93 ((Option (packed) #t)))
    (MessageField repeated sint32 packed_sint32_extension 94 ((Option (packed) #t)))
    (MessageField repeated sint64 packed_sint64_extension 95 ((Option (packed) #t)))
    (MessageField repeated fixed32 packed_fixed32_extension 96 ((Option (packed) #t)))
    (MessageField repeated fixed64 packed_fixed64_extension 97 ((Option (packed) #t)))
    (MessageField repeated sfixed32 packed_sfixed32_extension 98 ((Option (packed) #t)))
    (MessageField repeated sfixed64 packed_sfixed64_extension 99 ((Option (packed) #t)))
    (MessageField repeated float packed_float_extension 100 ((Option (packed) #t)))
    (MessageField repeated double packed_double_extension 101 ((Option (packed) #t)))
    (MessageField repeated bool packed_bool_extension 102 ((Option (packed) #t)))
    (MessageField repeated ForeignEnum packed_enum_extension 103 ((Option (packed) #t)))))
  (Message TestUnpackedExtensions () () () () (((Range 1 max))))
  (Extend
   TestUnpackedExtensions
   ((MessageField repeated int32 unpacked_int32_extension 90 ((Option (packed) #f)))
    (MessageField repeated int64 unpacked_int64_extension 91 ((Option (packed) #f)))
    (MessageField repeated uint32 unpacked_uint32_extension 92 ((Option (packed) #f)))
    (MessageField repeated uint64 unpacked_uint64_extension 93 ((Option (packed) #f)))
    (MessageField repeated sint32 unpacked_sint32_extension 94 ((Option (packed) #f)))
    (MessageField repeated sint64 unpacked_sint64_extension 95 ((Option (packed) #f)))
    (MessageField repeated fixed32 unpacked_fixed32_extension 96 ((Option (packed) #f)))
    (MessageField repeated fixed64 unpacked_fixed64_extension 97 ((Option (packed) #f)))
    (MessageField repeated sfixed32 unpacked_sfixed32_extension 98 ((Option (packed) #f)))
    (MessageField repeated sfixed64 unpacked_sfixed64_extension 99 ((Option (packed) #f)))
    (MessageField repeated float unpacked_float_extension 100 ((Option (packed) #f)))
    (MessageField repeated double unpacked_double_extension 101 ((Option (packed) #f)))
    (MessageField repeated bool unpacked_bool_extension 102 ((Option (packed) #f)))
    (MessageField repeated ForeignEnum unpacked_enum_extension 103 ((Option (packed) #f)))))
  (Message
   TestDynamicExtensions
   ((Enum
     DynamicEnumType
     ((EnumField DYNAMIC_FOO 2200 ()) (EnumField DYNAMIC_BAR 2201 ()) (EnumField DYNAMIC_BAZ 2202 ()))
     ()
     ())
    (Message DynamicMessageType () ((MessageField optional int32 dynamic_field 2100 ())) () () ()))
   ((MessageField optional fixed32 scalar_extension 2000 ())
    (MessageField optional ForeignEnum enum_extension 2001 ())
    (MessageField optional DynamicEnumType dynamic_enum_extension 2002 ())
    (MessageField optional ForeignMessage message_extension 2003 ())
    (MessageField optional DynamicMessageType dynamic_message_extension 2004 ())
    (MessageField repeated string repeated_extension 2005 ())
    (MessageField repeated sint32 packed_extension 2006 ((Option (packed) #t))))
   ()
   ()
   ())
  (Message
   TestRepeatedScalarDifferentTagSizes
   ()
   ((MessageField repeated fixed32 repeated_fixed32 12 ())
    (MessageField repeated int32 repeated_int32 13 ())
    (MessageField repeated fixed64 repeated_fixed64 2046 ())
    (MessageField repeated int64 repeated_int64 2047 ())
    (MessageField repeated float repeated_float 262142 ())
    (MessageField repeated uint64 repeated_uint64 262143 ()))
   ()
   ()
   ())
  (Message
   TestParsingMerge
   ((Message
     RepeatedFieldsGenerator
     ()
     ((MessageField repeated TestAllTypes field1 1 ())
      (MessageField repeated TestAllTypes field2 2 ())
      (MessageField repeated TestAllTypes field3 3 ())
      (MessageGroupField repeated Group1 10 () ((MessageField optional TestAllTypes field1 11 ())) () () ())
      (MessageGroupField repeated Group2 20 () ((MessageField optional TestAllTypes field1 21 ())) () () ())
      (MessageField repeated TestAllTypes ext1 1000 ())
      (MessageField repeated TestAllTypes ext2 1001 ()))
     ()
     ()
     ())
    (Extend
     TestParsingMerge
     ((MessageField optional TestAllTypes optional_ext 1000 ())
      (MessageField repeated TestAllTypes repeated_ext 1001 ()))))
   ((MessageField required TestAllTypes required_all_types 1 ())
    (MessageField optional TestAllTypes optional_all_types 2 ())
    (MessageField repeated TestAllTypes repeated_all_types 3 ())
    (MessageGroupField
     optional
     OptionalGroup
     10
     ()
     ((MessageField optional TestAllTypes optional_group_all_types 11 ()))
     ()
     ()
     ())
    (MessageGroupField
     repeated
     RepeatedGroup
     20
     ()
     ((MessageField optional TestAllTypes repeated_group_all_types 21 ()))
     ()
     ()
     ()))
   ()
   ()
   (((Range 1000 max))))
  (Message TestMergeException () ((MessageField optional TestAllExtensions all_extensions 1 ())) () () ())
  (Message
   TestCommentInjectionMessage
   ()
   ((MessageField optional string a 1 ((Option (default) "*/ <- Neither should this."))))
   ()
   ()
   ())
  (Message
   TestMessageSize
   ()
   ((MessageField optional bool m1 1 ())
    (MessageField optional int64 m2 2 ())
    (MessageField optional bool m3 3 ())
    (MessageField optional string m4 4 ())
    (MessageField optional int32 m5 5 ())
    (MessageField optional int64 m6 6 ()))
   ()
   ()
   ())
  (Message FooRequest () () () () ())
  (Message FooResponse () () () () ())
  (Message FooClientMessage () () () () ())
  (Message FooServerMessage () () () () ())
  (Service TestService ((RPC Foo #f FooRequest #f FooResponse ()) (RPC Bar #f BarRequest #f BarResponse ())) () ())
  (Message BarRequest () () () () ())
  (Message BarResponse () () () () ())
  (Message
   TestJsonName
   ()
   ((MessageField optional int32 field_name1 1 ())
    (MessageField optional int32 fieldName2 2 ())
    (MessageField optional int32 FieldName3 3 ())
    (MessageField optional int32 _field_name4 4 ())
    (MessageField optional int32 FIELD_NAME5 5 ())
    (MessageField optional int32 field_name6 6 ((Option (json_name) "@type")))
    (MessageField optional int32 fieldname7 7 ()))
   ()
   ()
   ())
  (Message
   TestHugeFieldNumbers
   ()
   ((MessageField optional int32 optional_int32 536870000 ())
    (MessageField optional int32 fixed_32 536870001 ())
    (MessageField repeated int32 repeated_int32 536870002 ((Option (packed) #f)))
    (MessageField repeated int32 packed_int32 536870003 ((Option (packed) #t)))
    (MessageField optional ForeignEnum optional_enum 536870004 ())
    (MessageField optional string optional_string 536870005 ())
    (MessageField optional bytes optional_bytes 536870006 ())
    (MessageField optional ForeignMessage optional_message 536870007 ())
    (MessageGroupField optional OptionalGroup 536870008 () ((MessageField optional int32 group_a 536870009 ())) () () ())
    (MessageMapField string string string_string_map 536870010 ())
    (MessageOneOfField
     oneof_field
     ((MessageField optional uint32 oneof_uint32 536870011 ())
      (MessageField optional TestAllTypes oneof_test_all_types 536870012 ())
      (MessageField optional string oneof_string 536870013 ())
      (MessageField optional bytes oneof_bytes 536870014 ()))))
   ()
   ()
   (((Range 536860000 536869999))))
  (Extend TestHugeFieldNumbers ((MessageField optional TestAllTypes test_all_types 536860000 ())))
  (Message
   TestExtensionInsideTable
   ()
   ((MessageField optional int32 field1 1 ())
    (MessageField optional int32 field2 2 ())
    (MessageField optional int32 field3 3 ())
    (MessageField optional int32 field4 4 ())
    (MessageField optional int32 field6 6 ())
    (MessageField optional int32 field7 7 ())
    (MessageField optional int32 field8 8 ())
    (MessageField optional int32 field9 9 ())
    (MessageField optional int32 field10 10 ()))
   ()
   ()
   (((Range 5 5))))
  (Extend TestExtensionInsideTable ((MessageField optional int32 test_extension_inside_table_extension 5 ())))
  (Message
   TestNestedGroupExtensionOuter
   ()
   ((MessageGroupField
     optional
     Layer1OptionalGroup
     1
     ()
     ((MessageGroupField repeated Layer2RepeatedGroup 2 () ((MessageField optional string another_field 6 ())) () () ((3)))
      (MessageGroupField
       repeated
       Layer2AnotherOptionalRepeatedGroup
       4
       ()
       ((MessageField optional string but_why_tho 5 ()))
       ()
       ()
       ()))
     ()
     ()
     ()))
   ()
   ()
   ())
  (Message TestNestedGroupExtensionInnerExtension () ((MessageField optional string inner_name 1 ())) () () ())
  (Extend
   TestNestedGroupExtensionOuter.Layer1OptionalGroup.Layer2RepeatedGroup
   ((MessageField optional TestNestedGroupExtensionInnerExtension inner 3 ())))
  (Enum
   VeryLargeEnum
   ((EnumField ENUM_LABEL_DEFAULT 0 ())
    (EnumField ENUM_LABEL_1 1 ())
    (EnumField ENUM_LABEL_2 2 ())
    (EnumField ENUM_LABEL_3 3 ())
    (EnumField ENUM_LABEL_4 4 ())
    (EnumField ENUM_LABEL_5 5 ())
    (EnumField ENUM_LABEL_6 6 ())
    (EnumField ENUM_LABEL_7 7 ())
    (EnumField ENUM_LABEL_8 8 ())
    (EnumField ENUM_LABEL_9 9 ())
    (EnumField ENUM_LABEL_10 10 ())
    (EnumField ENUM_LABEL_11 11 ())
    (EnumField ENUM_LABEL_12 12 ())
    (EnumField ENUM_LABEL_13 13 ())
    (EnumField ENUM_LABEL_14 14 ())
    (EnumField ENUM_LABEL_15 15 ())
    (EnumField ENUM_LABEL_16 16 ())
    (EnumField ENUM_LABEL_17 17 ())
    (EnumField ENUM_LABEL_18 18 ())
    (EnumField ENUM_LABEL_19 19 ())
    (EnumField ENUM_LABEL_20 20 ())
    (EnumField ENUM_LABEL_21 21 ())
    (EnumField ENUM_LABEL_22 22 ())
    (EnumField ENUM_LABEL_23 23 ())
    (EnumField ENUM_LABEL_24 24 ())
    (EnumField ENUM_LABEL_25 25 ())
    (EnumField ENUM_LABEL_26 26 ())
    (EnumField ENUM_LABEL_27 27 ())
    (EnumField ENUM_LABEL_28 28 ())
    (EnumField ENUM_LABEL_29 29 ())
    (EnumField ENUM_LABEL_30 30 ())
    (EnumField ENUM_LABEL_31 31 ())
    (EnumField ENUM_LABEL_32 32 ())
    (EnumField ENUM_LABEL_33 33 ())
    (EnumField ENUM_LABEL_34 34 ())
    (EnumField ENUM_LABEL_35 35 ())
    (EnumField ENUM_LABEL_36 36 ())
    (EnumField ENUM_LABEL_37 37 ())
    (EnumField ENUM_LABEL_38 38 ())
    (EnumField ENUM_LABEL_39 39 ())
    (EnumField ENUM_LABEL_40 40 ())
    (EnumField ENUM_LABEL_41 41 ())
    (EnumField ENUM_LABEL_42 42 ())
    (EnumField ENUM_LABEL_43 43 ())
    (EnumField ENUM_LABEL_44 44 ())
    (EnumField ENUM_LABEL_45 45 ())
    (EnumField ENUM_LABEL_46 46 ())
    (EnumField ENUM_LABEL_47 47 ())
    (EnumField ENUM_LABEL_48 48 ())
    (EnumField ENUM_LABEL_49 49 ())
    (EnumField ENUM_LABEL_50 50 ())
    (EnumField ENUM_LABEL_51 51 ())
    (EnumField ENUM_LABEL_52 52 ())
    (EnumField ENUM_LABEL_53 53 ())
    (EnumField ENUM_LABEL_54 54 ())
    (EnumField ENUM_LABEL_55 55 ())
    (EnumField ENUM_LABEL_56 56 ())
    (EnumField ENUM_LABEL_57 57 ())
    (EnumField ENUM_LABEL_58 58 ())
    (EnumField ENUM_LABEL_59 59 ())
    (EnumField ENUM_LABEL_60 60 ())
    (EnumField ENUM_LABEL_61 61 ())
    (EnumField ENUM_LABEL_62 62 ())
    (EnumField ENUM_LABEL_63 63 ())
    (EnumField ENUM_LABEL_64 64 ())
    (EnumField ENUM_LABEL_65 65 ())
    (EnumField ENUM_LABEL_66 66 ())
    (EnumField ENUM_LABEL_67 67 ())
    (EnumField ENUM_LABEL_68 68 ())
    (EnumField ENUM_LABEL_69 69 ())
    (EnumField ENUM_LABEL_70 70 ())
    (EnumField ENUM_LABEL_71 71 ())
    (EnumField ENUM_LABEL_72 72 ())
    (EnumField ENUM_LABEL_73 73 ())
    (EnumField ENUM_LABEL_74 74 ())
    (EnumField ENUM_LABEL_75 75 ())
    (EnumField ENUM_LABEL_76 76 ())
    (EnumField ENUM_LABEL_77 77 ())
    (EnumField ENUM_LABEL_78 78 ())
    (EnumField ENUM_LABEL_79 79 ())
    (EnumField ENUM_LABEL_80 80 ())
    (EnumField ENUM_LABEL_81 81 ())
    (EnumField ENUM_LABEL_82 82 ())
    (EnumField ENUM_LABEL_83 83 ())
    (EnumField ENUM_LABEL_84 84 ())
    (EnumField ENUM_LABEL_85 85 ())
    (EnumField ENUM_LABEL_86 86 ())
    (EnumField ENUM_LABEL_87 87 ())
    (EnumField ENUM_LABEL_88 88 ())
    (EnumField ENUM_LABEL_89 89 ())
    (EnumField ENUM_LABEL_90 90 ())
    (EnumField ENUM_LABEL_91 91 ())
    (EnumField ENUM_LABEL_92 92 ())
    (EnumField ENUM_LABEL_93 93 ())
    (EnumField ENUM_LABEL_94 94 ())
    (EnumField ENUM_LABEL_95 95 ())
    (EnumField ENUM_LABEL_96 96 ())
    (EnumField ENUM_LABEL_97 97 ())
    (EnumField ENUM_LABEL_98 98 ())
    (EnumField ENUM_LABEL_99 99 ())
    (EnumField ENUM_LABEL_100 100 ()))
   ()
   ())
  (Message
   TestExtensionRangeSerialize
   ((Extend
     TestExtensionRangeSerialize
     ((MessageField optional int32 bar_one 2 ())
      (MessageField optional int32 bar_two 4 ())
      (MessageField optional int32 bar_three 10 ())
      (MessageField optional int32 bar_four 15 ())
      (MessageField optional int32 bar_five 19 ()))))
   ((MessageField optional int32 foo_one 1 ())
    (MessageField optional int32 foo_two 6 ())
    (MessageField optional int32 foo_three 7 ())
    (MessageField optional int32 foo_four 13 ()))
   ()
   ()
   (((Range 2 2)) ((Range 3 4)) ((Range 9 10)) ((Range 15 15)) ((Range 17 17)) ((Range 19 19))))
  (Message
   TestVerifyInt32Simple
   ()
   ((MessageField optional int32 optional_int32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ()))
   ()
   ()
   ())
  (Message
   TestVerifyInt32
   ()
   ((MessageField optional int32 optional_int32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyMostlyInt32
   ()
   ((MessageField optional int64 optional_int64_30 30 ())
    (MessageField optional int32 optional_int32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_3 3 ())
    (MessageField optional int32 optional_int32_4 4 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyMostlyInt32BigFieldNumber
   ()
   ((MessageField optional int64 optional_int64_30 30 ())
    (MessageField optional int32 optional_int32_300 300 ())
    (MessageField optional int32 optional_int32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_3 3 ())
    (MessageField optional int32 optional_int32_4 4 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyUint32Simple
   ()
   ((MessageField optional uint32 optional_uint32_1 1 ())
    (MessageField optional uint32 optional_uint32_2 2 ())
    (MessageField optional uint32 optional_uint32_63 63 ())
    (MessageField optional uint32 optional_uint32_64 64 ()))
   ()
   ()
   ())
  (Message
   TestVerifyUint32
   ()
   ((MessageField optional uint32 optional_uint32_1 1 ())
    (MessageField optional uint32 optional_uint32_2 2 ())
    (MessageField optional uint32 optional_uint32_63 63 ())
    (MessageField optional uint32 optional_uint32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyOneUint32
   ()
   ((MessageField optional uint32 optional_uint32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyOneInt32BigFieldNumber
   ()
   ((MessageField optional int32 optional_int32_65 65 ())
    (MessageField optional int64 optional_int64_1 1 ())
    (MessageField optional int64 optional_int64_2 2 ())
    (MessageField optional int64 optional_int64_63 63 ())
    (MessageField optional int64 optional_int64_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyInt32BigFieldNumber
   ()
   ((MessageField optional int32 optional_int32_1000 1000 ())
    (MessageField optional int32 optional_int32_65 65 ())
    (MessageField optional int32 optional_int32_1 1 ())
    (MessageField optional int32 optional_int32_2 2 ())
    (MessageField optional int32 optional_int32_63 63 ())
    (MessageField optional int32 optional_int32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyUint32BigFieldNumber
   ()
   ((MessageField optional uint32 optional_uint32_1000 1000 ())
    (MessageField optional uint32 optional_uint32_65 65 ())
    (MessageField optional uint32 optional_uint32_1 1 ())
    (MessageField optional uint32 optional_uint32_2 2 ())
    (MessageField optional uint32 optional_uint32_63 63 ())
    (MessageField optional uint32 optional_uint32_64 64 ())
    (MessageField optional TestAllTypes optional_all_types 9 ())
    (MessageField repeated TestAllTypes repeated_all_types 10 ()))
   ()
   ()
   ())
  (Message
   TestVerifyBigFieldNumberUint32
   ((Message
     Nested
     ()
     ((MessageField optional uint32 optional_uint32_5000 5000 ())
      (MessageField optional uint32 optional_uint32_1000 1000 ())
      (MessageField optional uint32 optional_uint32_66 66 ())
      (MessageField optional uint32 optional_uint32_65 65 ())
      (MessageField optional uint32 optional_uint32_1 1 ())
      (MessageField optional uint32 optional_uint32_2 2 ())
      (MessageField optional uint32 optional_uint32_63 63 ())
      (MessageField optional uint32 optional_uint32_64 64 ())
      (MessageField optional Nested optional_nested 9 ())
      (MessageField repeated Nested repeated_nested 10 ()))
     ()
     ()
     ()))
   ((MessageField optional Nested optional_nested 1 ()))
   ()
   ()
   ())
  (Message
   EnumParseTester
   ((Enum
     SeqSmall0
     ((EnumField SEQ_SMALL_0_DEFAULT 0 ()) (EnumField SEQ_SMALL_0_1 1 ()) (EnumField SEQ_SMALL_0_2 2 ()))
     ()
     ())
    (Enum
     SeqSmall1
     ((EnumField SEQ_SMALL_1_DEFAULT 1 ()) (EnumField SEQ_SMALL_1_2 2 ()) (EnumField SEQ_SMALL_1_3 3 ()))
     ()
     ())
    (Enum
     SeqLarge
     ((EnumField SEQ_LARGE_DEFAULT -1 ())
      (EnumField SEQ_LARGE_0 0 ())
      (EnumField SEQ_LARGE_1 1 ())
      (EnumField SEQ_LARGE_2 2 ())
      (EnumField SEQ_LARGE_3 3 ())
      (EnumField SEQ_LARGE_4 4 ())
      (EnumField SEQ_LARGE_5 5 ())
      (EnumField SEQ_LARGE_6 6 ())
      (EnumField SEQ_LARGE_7 7 ())
      (EnumField SEQ_LARGE_8 8 ())
      (EnumField SEQ_LARGE_9 9 ())
      (EnumField SEQ_LARGE_10 10 ())
      (EnumField SEQ_LARGE_11 11 ())
      (EnumField SEQ_LARGE_12 12 ())
      (EnumField SEQ_LARGE_13 13 ())
      (EnumField SEQ_LARGE_14 14 ())
      (EnumField SEQ_LARGE_15 15 ())
      (EnumField SEQ_LARGE_16 16 ())
      (EnumField SEQ_LARGE_17 17 ())
      (EnumField SEQ_LARGE_18 18 ())
      (EnumField SEQ_LARGE_19 19 ())
      (EnumField SEQ_LARGE_20 20 ())
      (EnumField SEQ_LARGE_21 21 ())
      (EnumField SEQ_LARGE_22 22 ())
      (EnumField SEQ_LARGE_23 23 ())
      (EnumField SEQ_LARGE_24 24 ())
      (EnumField SEQ_LARGE_25 25 ())
      (EnumField SEQ_LARGE_26 26 ())
      (EnumField SEQ_LARGE_27 27 ())
      (EnumField SEQ_LARGE_28 28 ())
      (EnumField SEQ_LARGE_29 29 ())
      (EnumField SEQ_LARGE_30 30 ())
      (EnumField SEQ_LARGE_31 31 ())
      (EnumField SEQ_LARGE_32 32 ())
      (EnumField SEQ_LARGE_33 33 ()))
     ()
     ())
    (Enum
     Arbitrary
     ((EnumField ARBITRARY_DEFAULT -123123 ())
      (EnumField ARBITRARY_1 -123 ())
      (EnumField ARBITRARY_2 213 ())
      (EnumField ARBITRARY_3 213213 ())
      (EnumField ARBITRARY_MIN -2147483648 ())
      (EnumField ARBITRARY_MAX 2147483647 ()))
     ()
     ()))
   ((MessageField optional SeqSmall0 optional_seq_small_0_lowfield 1 ())
    (MessageField optional SeqSmall0 optional_seq_small_0_midfield 1001 ())
    (MessageField optional SeqSmall0 optional_seq_small_0_hifield 1000001 ())
    (MessageField repeated SeqSmall0 repeated_seq_small_0_lowfield 2 ())
    (MessageField repeated SeqSmall0 repeated_seq_small_0_midfield 1002 ())
    (MessageField repeated SeqSmall0 repeated_seq_small_0_hifield 1000002 ())
    (MessageField repeated SeqSmall0 packed_seq_small_0_lowfield 3 ((Option (packed) #t)))
    (MessageField repeated SeqSmall0 packed_seq_small_0_midfield 1003 ((Option (packed) #t)))
    (MessageField repeated SeqSmall0 packed_seq_small_0_hifield 1000003 ((Option (packed) #t)))
    (MessageField optional SeqSmall1 optional_seq_small_1_lowfield 4 ())
    (MessageField optional SeqSmall1 optional_seq_small_1_midfield 1004 ())
    (MessageField optional SeqSmall1 optional_seq_small_1_hifield 1000004 ())
    (MessageField repeated SeqSmall1 repeated_seq_small_1_lowfield 5 ())
    (MessageField repeated SeqSmall1 repeated_seq_small_1_midfield 1005 ())
    (MessageField repeated SeqSmall1 repeated_seq_small_1_hifield 1000005 ())
    (MessageField repeated SeqSmall1 packed_seq_small_1_lowfield 6 ((Option (packed) #t)))
    (MessageField repeated SeqSmall1 packed_seq_small_1_midfield 1006 ((Option (packed) #t)))
    (MessageField repeated SeqSmall1 packed_seq_small_1_hifield 1000006 ((Option (packed) #t)))
    (MessageField optional SeqLarge optional_seq_large_lowfield 7 ())
    (MessageField optional SeqLarge optional_seq_large_midfield 1007 ())
    (MessageField optional SeqLarge optional_seq_large_hifield 1000007 ())
    (MessageField repeated SeqLarge repeated_seq_large_lowfield 8 ())
    (MessageField repeated SeqLarge repeated_seq_large_midfield 1008 ())
    (MessageField repeated SeqLarge repeated_seq_large_hifield 1000008 ())
    (MessageField repeated SeqLarge packed_seq_large_lowfield 9 ((Option (packed) #t)))
    (MessageField repeated SeqLarge packed_seq_large_midfield 1009 ((Option (packed) #t)))
    (MessageField repeated SeqLarge packed_seq_large_hifield 1000009 ((Option (packed) #t)))
    (MessageField optional Arbitrary optional_arbitrary_lowfield 10 ())
    (MessageField optional Arbitrary optional_arbitrary_midfield 1010 ())
    (MessageField optional Arbitrary optional_arbitrary_hifield 1000010 ())
    (MessageField repeated Arbitrary repeated_arbitrary_lowfield 11 ())
    (MessageField repeated Arbitrary repeated_arbitrary_midfield 1011 ())
    (MessageField repeated Arbitrary repeated_arbitrary_hifield 1000011 ())
    (MessageField repeated Arbitrary packed_arbitrary_lowfield 12 ((Option (packed) #t)))
    (MessageField repeated Arbitrary packed_arbitrary_midfield 1012 ((Option (packed) #t)))
    (MessageField repeated Arbitrary packed_arbitrary_hifield 1000012 ((Option (packed) #t)))
    (MessageField optional int32 other_field 99 ()))
   ()
   ()
   ())))
